// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appinftest.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB_IOSInfInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AppinftestRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface AppinftestRoot : GPBRootObject
@end

#pragma mark - PB_IOSInfInfo

typedef GPB_ENUM(PB_IOSInfInfo_FieldNumber) {
  PB_IOSInfInfo_FieldNumber_ClassName = 1,
  PB_IOSInfInfo_FieldNumber_MethodName = 2,
};

@interface PB_IOSInfInfo : GPBMessage

/// 类名
@property(nonatomic, readwrite, copy, null_resettable) NSString *className;
/// Test to see if @c className has been set.
@property(nonatomic, readwrite) BOOL hasClassName;

/// 方法名
@property(nonatomic, readwrite, copy, null_resettable) NSString *methodName;
/// Test to see if @c methodName has been set.
@property(nonatomic, readwrite) BOOL hasMethodName;

@end

#pragma mark - PB_SendIOSInfReq

typedef GPB_ENUM(PB_SendIOSInfReq_FieldNumber) {
  PB_SendIOSInfReq_FieldNumber_IOsInfoArray = 1,
};

@interface PB_SendIOSInfReq : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PB_IOSInfInfo*> *iOsInfoArray;
/// The number of items in @c iOsInfoArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger iOsInfoArray_Count;

@end

#pragma mark - PB_SendIOSInfRsp

typedef GPB_ENUM(PB_SendIOSInfRsp_FieldNumber) {
  PB_SendIOSInfRsp_FieldNumber_Result = 1,
};

@interface PB_SendIOSInfRsp : GPBMessage

///	返回结果。 值为负数则出错。
@property(nonatomic, readwrite) int32_t result;

@property(nonatomic, readwrite) BOOL hasResult;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
