// Code generated by protoc-gen-go.
// source: appinftest.proto
// DO NOT EDIT!

/*
Package com_sangfor_moa_protobuf is a generated protocol buffer package.

It is generated from these files:
	appinftest.proto

It has these top-level messages:
	PB_IOSInfInfo
	PB_SendIOSInfReq
	PB_SendIOSInfRsp
*/
package com_sangfor_moa_protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_IOSInfInfo struct {
	ClassName        *string `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	MethodName       *string `protobuf:"bytes,2,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PB_IOSInfInfo) Reset()                    { *m = PB_IOSInfInfo{} }
func (m *PB_IOSInfInfo) String() string            { return proto.CompactTextString(m) }
func (*PB_IOSInfInfo) ProtoMessage()               {}
func (*PB_IOSInfInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PB_IOSInfInfo) GetClassName() string {
	if m != nil && m.ClassName != nil {
		return *m.ClassName
	}
	return ""
}

func (m *PB_IOSInfInfo) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

type PB_SendIOSInfReq struct {
	IOSInfo          []*PB_IOSInfInfo `protobuf:"bytes,1,rep,name=iOS_info,json=iOSInfo" json:"iOS_info,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PB_SendIOSInfReq) Reset()                    { *m = PB_SendIOSInfReq{} }
func (m *PB_SendIOSInfReq) String() string            { return proto.CompactTextString(m) }
func (*PB_SendIOSInfReq) ProtoMessage()               {}
func (*PB_SendIOSInfReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PB_SendIOSInfReq) GetIOSInfo() []*PB_IOSInfInfo {
	if m != nil {
		return m.IOSInfo
	}
	return nil
}

type PB_SendIOSInfRsp struct {
	Result           *int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PB_SendIOSInfRsp) Reset()                    { *m = PB_SendIOSInfRsp{} }
func (m *PB_SendIOSInfRsp) String() string            { return proto.CompactTextString(m) }
func (*PB_SendIOSInfRsp) ProtoMessage()               {}
func (*PB_SendIOSInfRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PB_SendIOSInfRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*PB_IOSInfInfo)(nil), "com.sangfor.moa.protobuf.PB_IOSInfInfo")
	proto.RegisterType((*PB_SendIOSInfReq)(nil), "com.sangfor.moa.protobuf.PB_SendIOSInfReq")
	proto.RegisterType((*PB_SendIOSInfRsp)(nil), "com.sangfor.moa.protobuf.PB_SendIOSInfRsp")
}

func init() { proto.RegisterFile("appinftest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2c, 0x28, 0xc8,
	0xcc, 0x4b, 0x2b, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xce,
	0xcf, 0xd5, 0x2b, 0x4e, 0xcc, 0x4b, 0x4f, 0xcb, 0x2f, 0xd2, 0xcb, 0xcd, 0x4f, 0x84, 0x08, 0x27,
	0x95, 0xa6, 0x29, 0xf9, 0x73, 0xf1, 0x06, 0x38, 0xc5, 0x7b, 0xfa, 0x07, 0x7b, 0xe6, 0xa5, 0x01,
	0x51, 0xbe, 0x90, 0x2c, 0x17, 0x57, 0x72, 0x4e, 0x62, 0x71, 0x71, 0x7c, 0x5e, 0x62, 0x6e, 0xaa,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x27, 0x58, 0xc4, 0x0f, 0x28, 0x20, 0x24, 0xcf, 0xc5,
	0x9d, 0x9b, 0x5a, 0x92, 0x91, 0x9f, 0x02, 0x91, 0x67, 0x02, 0xcb, 0x73, 0x41, 0x84, 0x40, 0x0a,
	0x94, 0xc2, 0xb8, 0x04, 0x80, 0x06, 0x06, 0xa7, 0xe6, 0xa5, 0x40, 0x0c, 0x0d, 0x4a, 0x2d, 0x14,
	0x72, 0xe2, 0xe2, 0xc8, 0xf4, 0x0f, 0x8e, 0x07, 0xba, 0x29, 0x1f, 0x68, 0x22, 0xb3, 0x06, 0xb7,
	0x91, 0xba, 0x1e, 0x2e, 0x17, 0xe9, 0xa1, 0x38, 0x27, 0x88, 0x3d, 0x13, 0xcc, 0xce, 0x57, 0xd2,
	0x42, 0x37, 0xb7, 0xb8, 0x40, 0x48, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x04, 0xec,
	0x4e, 0xd6, 0x20, 0x28, 0x0f, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x77, 0xe9, 0xb8, 0x01, 0x01,
	0x00, 0x00,
}
